name: Redocly Publish
run-name: ${{ github.actor }} triggered Redocly build 🚀
on: [push]
jobs:
  build-redocly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
