name: Redocly Publish
run-name: ${{ github.actor }} triggered Redocly build 🚀
on: [push]
jobs:
  build-redocly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5
      - name: Upload Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./site"
      - name: Update CHANGELOG
        if: startsWith(github.event.ref, 'refs/tags/v')
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          includeInvalidCommits: true
          excludeTypes: ""
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - uses: ncipollo/release-action@v1
        if: startsWith(github.event.ref, 'refs/tags/v')
        with:
          artifacts: "site/openapi.yaml"
          artifactContentType: "application/yaml"
          replacesArtifacts: true
          removeArtifacts: true
          allowUpdates: true
          draft: false
          makeLatest: true
          body: ${{ steps.changelog.outputs.changes }}
      - name: Commit CHANGELOG.md
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
      - name: Copy openapi to release location
        if: startsWith(github.event.ref, 'refs/tags/v')
        run: "cp site/openapi.yaml site/releases/openapi-${{ github.ref_name }}.yaml"
      - name: Commit Releases OpenAPI Specification
        if: startsWith(github.event.ref, 'refs/tags/v')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: "site/releases/openapi-${{ github.ref_name }}.yaml"
  deploy-pages:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-redocly
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

